# Part 1

In [3]:
# Advent of Code 2022, Day 2 Part 1
# https://adventofcode.com/2022/day/2

import pandas as pd
import numpy as np

In [16]:
# Open the file containing the strategy guide
with open('rps_strategy.txt', 'r') as f:
    data = f.read()
    lines = data.split('\n')

# Remove blank lines
lines = list(filter(None, lines))

In [19]:
# Create dataframe from strategy guide and rename the column
df = pd.DataFrame(lines).dropna()
df.columns=('strategy',)

df

     strategy
0         B Z
1         B Z
2         C Z
3         C Z
4         B X
...       ...
2495      C Z
2496      C Z
2497      B Z
2498      C Z
2499      A Y

[2500 rows x 1 columns]

In [20]:
# Rock paper scissors dictionary -
# 1 means the first player in the tuple wins.
# 2 means the second player wins.
# 0 indicates a draw.
winner_dict = {
    ('R','R'):0,
    ('R','P'):2,
    ('R','S'):1,
    ('P','R'):1,
    ('P','P'):0,
    ('P','S'):2,
    ('S','R'):2,
    ('S','P'):1,
    ('S','S'):0
}

In [25]:
opponent_shape_dict = {'A':'R', 'B':'P', 'C':'S'}
my_shape_dict = {'X':'R', 'Y':'P', 'Z':'S'}

def get_opponent_shape(s):
    # opponent shape is the first character of each line
    shape_coded = s[0]
    # decode opponent shape
    shape = opponent_shape_dict[shape_coded]
    return shape

def get_my_shape(s):
    # my shape is the last character of each line
    shape_coded = s[-1]
    # decode my shape
    shape = my_shape_dict[shape_coded]
    return shape

def get_rps_match(s):
    return (get_opponent_shape(s),get_my_shape(s))

def get_winner(s):
    rps_match = get_rps_match(s)
    return winner_dict[rps_match]

def get_my_wld(s):
    wld_dict = {0:'D', 1:'L', 2:'W'}
    wld_code = get_winner(s)
    return wld_dict[wld_code]

def get_opponent_wld(s):
    wld_dict = {0:'D', 1:'W', 2:'L'}
    wld_code = get_winner(s)
    return wld_dict[wld_code]

In [26]:
df['opponent']=df['strategy'].apply(get_opponent_shape)
df['me']=df['strategy'].apply(get_my_shape)

In [28]:
df['rps_match']=df['strategy'].apply(get_rps_match)

In [29]:
df['winner'] = df['strategy'].apply(get_winner)
df['opponent_wld'] = df['strategy'].apply(get_opponent_wld)
df['my_wld'] = df['strategy'].apply(get_my_wld)

df

     strategy opponent me rps_match  winner opponent_wld my_wld
0         B Z        P  S    (P, S)       2            L      W
1         B Z        P  S    (P, S)       2            L      W
2         C Z        S  S    (S, S)       0            D      D
3         C Z        S  S    (S, S)       0            D      D
4         B X        P  R    (P, R)       1            W      L
...       ...      ... ..       ...     ...          ...    ...
2495      C Z        S  S    (S, S)       0            D      D
2496      C Z        S  S    (S, S)       0            D      D
2497      B Z        P  S    (P, S)       2            L      W
2498      C Z        S  S    (S, S)       0            D      D
2499      A Y        R  P    (R, P)       2            L      W

[2500 rows x 7 columns]

In [30]:
# Assigning points

shape_score_dict = {'R':1, 'P':2, 'S':3}

winner_score_dict = {'L':0, 'D':3, 'W':6}

def get_shape_score(shape):
    return shape_score_dict[shape]

def get_winner_score(wld):
    return winner_score_dict[wld]

In [31]:
df['opponent_wld_points'] = df['opponent_wld'].apply(get_winner_score)
df['my_wld_points'] = df['my_wld'].apply(get_winner_score)

df['opponent_shape_points'] = df['opponent'].apply(get_shape_score)
df['my_shape_points'] = df['me'].apply(get_shape_score)

df

,strategy,opponent,me,rps_match,winner,opponent_wld,my_wld,opponent_wld_points,my_wld_points,opponent_shape_points,my_shape_points
0,B Z,P,S,"(P, S)",2,L,W,0,6,2,3
1,B Z,P,S,"(P, S)",2,L,W,0,6,2,3
2,C Z,S,S,"(S, S)",0,D,D,3,3,3,3
3,C Z,S,S,"(S, S)",0,D,D,3,3,3,3
4,B X,P,R,"(P, R)",1,W,L,6,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
2495,C Z,S,S,"(S, S)",0,D,D,3,3,3,3
2496,C Z,S,S,"(S, S)",0,D,D,3,3,3,3
2497,B Z,P,S,"(P, S)",2,L,W,0,6,2,3
2498,C Z,S,S,"(S, S)",0,D,D,3,3,3,3
2499,A Y,R,P,"(R, P)",2,L,W,0,6,1,2

In [32]:
df['my_total_points'] = df['my_shape_points']+df['my_wld_points']
df['opponent_total_points'] = df['opponent_shape_points']+df['opponent_wld_points']

In [34]:
my_grand_total_points = df['my_total_points'].sum()
opponent_grand_total_points = df['opponent_total_points'].sum()

In [35]:
my_grand_total_points

15523

In [37]:
opponent_grand_total_points

11536

# Part 2

In [39]:
# Advent of Code 2022, Day 2 Part 2
# https://adventofcode.com/2022/day/2#part2

# set up a new dataframe from the original strategy guide

# Open the file containing the strategy guide
with open('rps_strategy.txt', 'r') as f:
    data = f.read()
    lines = data.split('\n')

# Remove blank lines
lines = list(filter(None, lines))

In [42]:
df2 = pd.DataFrame(lines).dropna()
df2.columns=('strategy',)

In [43]:
df2['opponent'] = df2['strategy'].apply(get_opponent_shape)

df2

     strategy opponent
0         B Z        P
1         B Z        P
2         C Z        S
3         C Z        S
4         B X        P
...       ...      ...
2495      C Z        S
2496      C Z        S
2497      B Z        P
2498      C Z        S
2499      A Y        R

[2500 rows x 2 columns]

In [47]:
# What shape do I need to achieve the goal?

# key = (<opponent shape>, <win/lose/draw goal>)
# value = my shape to meet the goal

my_goal_shape_dict = {
    ('R','W'):'P',
    ('R','L'):'S',
    ('R','D'):'R',
    ('P','W'):'S',
    ('P','L'):'R',
    ('P','D'):'P',
    ('S','W'):'R',
    ('S','L'):'P',
    ('S','D'):'S'
    }

In [48]:
# Goal for each round:  Win, lose or draw?
def get_my_wld_goal(s):
    my_wld_goal_dict = {'X':'L', 'Y':'D', 'Z':'W'}
    # wld goal is the last character
    goal_code = s[-1]
    goal = my_wld_goal_dict[goal_code]
    return goal

df2['my_wld_goal'] = df2['strategy'].apply(get_my_wld_goal)

def get_opponent_goal_pair(s):
    return (get_opponent_shape(s), get_my_wld_goal(s))

def get_my_goal_shape(s):
    return my_goal_shape_dict[get_opponent_goal_pair(s)]


def get_opponent_wld_2(s):
    wld_opposite_dict = {'W':'L', 'L':'W','D':'D'}
    my_wld = get_my_wld_goal(s)
    return wld_opposite_dict[my_wld]

In [49]:

df2['opponent-goal_pair'] = df2['strategy'].apply(get_opponent_goal_pair)
df2['me'] = df2['strategy'].apply(get_my_goal_shape)

In [50]:
def get_rps_match_goal(s):
    return (get_opponent_shape(s),get_my_goal_shape(s))

def get_winner_goal(s):
    rps_match = get_rps_match_goal(s)
    return winner_dict[rps_match]

df2['rps_match'] = df2['strategy'].apply(get_rps_match_goal)
df2['winner'] = df2['strategy'].apply(get_winner_goal)

In [52]:
df2['opponent_wld'] = df2['strategy'].apply(get_opponent_wld_2)

df2['opponent_wld_points'] = df2['opponent_wld'].apply(get_winner_score)
df2['my_wld_points'] = df2['my_wld_goal'].apply(get_winner_score)

df2['opponent_shape_points'] = df2['opponent'].apply(get_shape_score)
df2['my_shape_points'] = df2['me'].apply(get_shape_score)

df2['my_total_points'] = df2['my_shape_points']+df2['my_wld_points']
df2['opponent_total_points'] = df2['opponent_shape_points']+df2['opponent_wld_points']

In [54]:
my_grand_total_points_2 = df2['my_total_points'].sum()
opponent_grand_total_points_2 = df2['opponent_total_points'].sum()

In [55]:
my_grand_total_points_2

15702

In [56]:
opponent_grand_total_points_2

9379